[package]
name = "himalaya"
description = "CLI to manage emails."
version = "0.9.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-interface", "command-line-utilities", "email"]
keywords = ["cli", "mail", "email", "client", "imap"]
homepage = "https://pimalaya.org/himalaya"
documentation = "https://pimalaya.org/himalaya/"
repository = "https://github.com/soywod/himalaya/"
metadata.docs.rs.all-features = true

[features]
default = [
  "imap-backend",
  # "notmuch-backend",
  "smtp-sender",
  # "pgp-commands",
  # "pgp-gpg",
  # "pgp-native",
]
imap-backend = ["email-lib/imap-backend"]
notmuch-backend = ["email-lib/notmuch-backend"]
smtp-sender = ["email-lib/smtp-sender"]
pgp = []
pgp-commands = ["pgp", "email-lib/pgp-commands"]
pgp-gpg = ["pgp", "email-lib/pgp-gpg"]
pgp-native = ["pgp", "email-lib/pgp-native"]

# dev dependencies

[dev-dependencies.async-trait]
version = "0.1"

[dev-dependencies.tempfile]
version = "3.3"

# dependencies

[dependencies.anyhow]
version = "1.0"

[dependencies.async-trait]
version = "0.1"

[dependencies.atty]
version = "0.2"

[dependencies.chrono]
version = "0.4.24"

[dependencies.clap]
version = "4.0"

[dependencies.clap_complete]
version = "4.0"

[dependencies.clap_mangen]
version = "0.2"

[dependencies.console]
version = "0.15.2"

[dependencies.dialoguer]
version = "0.10.2"

[dependencies.dirs]
version = "4.0.0"

[dependencies.email_address]
version = "0.2.4"

[dependencies.env_logger]
version = "0.8"

[dependencies.erased-serde]
version = "0.3"

[dependencies.indicatif]
version = "0.17"

[dependencies.log]
version = "0.4"

[dependencies.md5]
version = "0.7.0"

[dependencies.once_cell]
version = "1.16.0"

[dependencies.email-lib]
# version = "=0.15.3"
default-features = false
path = "/home/soywod/sourcehut/pimalaya/email"

[dependencies.keyring-lib]
version = "=0.1.0"

[dependencies.oauth-lib]
# version = "=0.1.0"
path = "/home/soywod/sourcehut/pimalaya/oauth"

[dependencies.process-lib]
version = "=0.1.0"

[dependencies.mml-lib]
# version = "=1.0.1"
path = "/home/soywod/sourcehut/pimalaya/mml"

[dependencies.secret-lib]
version = "=0.1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.shellexpand-utils]
# version = "=0.1.0"
path = "/home/soywod/sourcehut/pimalaya/shellexpand-utils"

[dependencies.termcolor]
version = "1.1"

[dependencies.terminal_size]
version = "0.1"

[dependencies.tokio]
version = "1.23"
default-features = false
features = ["macros", "rt-multi-thread"]

[dependencies.toml]
version = "0.7.4"

[dependencies.toml_edit]
version = "0.19.8"

[dependencies.unicode-width]
version = "0.1"

[dependencies.url]
version = "2.2"

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[target.'cfg(target_env = "musl")'.dependencies.rusqlite]
version = "0.29"
features = []

[target.'cfg(not(target_env = "musl"))'.dependencies.rusqlite]
version = "0.29"
features = ["bundled"]

[target.'cfg(not(windows))'.dependencies.coredump]
version = "=0.1.2"
