[example]
default = true

# The display-name and email are used to build the full email address:
# "My example account" <example@localhost>
display-name = "My example account"
email = "example@localhost"

sync = true
sync-dir = "/tmp/himalaya-sync-example"

# The default backend used for all the features like adding folders,
# listing envelopes or copying messages.
backend = "imap"

# IMAP config
imap.host = "localhost"
imap.port = 3143
imap.login = "example@localhost"
imap.ssl = false
imap.starttls = false
imap.insecure = true
imap.auth = "passwd"
imap.passwd.keyring = "example-passwd"

# Override the backend used for sending messages.
message.send.backend = "smtp"

# SMTP config
smtp.host = "localhost"
smtp.port = 3025
smtp.login = "example@localhost"
smtp.ssl = false
smtp.starttls = false
smtp.insecure = true
smtp.auth = "passwd"
smtp.passwd.raw = "example"

[example-2]
display-name = "My example account 2"
email = "example2@localhost"

backend = "imap"

imap.host = "localhost"
imap.port = 3143
imap.login = "example2@localhost"
imap.ssl = false
imap.starttls = false
imap.insecure = true
imap.auth = "passwd"
imap.passwd.raw = "example"

message.send.backend = "sendmail"

sendmail.cmd = "sendmail"
