[example]
default = true

# The display-name and email are used to build the full email address:
# "My example account" <example@localhost>
display-name = "My example account"
email = "example@localhost"

# The default backend used for all the features like adding folders,
# listing envelopes or copying messages.
backend = "imap"

imap.host = "imap.gmail.com"
imap.port = 993
imap.login = "example@localhost"
imap.auth = "passwd"
# imap.Some.passwd.cmd = "pass show gmail"

