name: pre-release

on:
  push:

jobs:
  pre-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: aarch64-macos
            target: aarch64-apple-darwin
            os: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          enable_kvm: true
      - name: Cache Nix store
        uses: cachix/cachix-action@v15
        with:
          name: soywod
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - name: Build release
        run: |
          nix-build --argstr target ${{ matrix.target }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "himalaya-${{ matrix.system }}"
          path: |
            result/bin/himalaya*
            result/bin/share
